import * as React from 'react';
import { STATUS, TYPE } from './utils';
import { IProps, IState } from './types/common';
declare class SpotifyWebPlayer extends React.PureComponent<IProps, IState> {
    public componentDidMount(): Promise<void>;
    public componentDidUpdate(prevProps: IProps, prevState: IState): Promise<void>;
    public componentWillUnmount(): void;
    public render(): JSX.Element;
    private static defaultProps;
    private _isMounted;
    private emptyTrack;
    private hasNewToken;
    private player?;
    private playerProgressInterval?;
    private playerSyncInterval?;
    private syncTimeout?;
    private seekUpdateInterval;
    private readonly styles;
    private readonly isExternalPlayer;
    private readonly playOptions;
    private handleChangeRange;
    private handleClickTogglePlay;
    private handleClickPrevious;
    private handleClickNext;
    private handleClickDevice;
    private handleDeviceChange;
    private handleFavoriteStatusChange;
    private handlePlaybackStatus;
    private handlePlayerErrors;
    private handlePlayerStateChanges;
    private handlePlayerStatus;
    private handleToggleMagnify;
    private initializeDevices;
    private initializePlayer;
    private setAlbumImage;
    private setVolume;
    private syncDevice;
    private toggleOffset;
    private togglePlay;
    private updateSeekBar;
    private updateState;
    constructor(props: IProps);
}
export { STATUS, TYPE };
export default SpotifyWebPlayer;
